default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: footnote_development

test:
  <<: *default
  database: footnote_test

production:
  <<: *default
  database: footnote_production
  username: footnote
  password: <%= ENV['FOOTNOTE_DATABASE_PASSWORD'] %>
